import = ["~/.config/alacritty/rose-pine-moon.toml"]

[shell]
program = "/home/linuxbrew/.linuxbrew/bin/zellij"
# args = ["cd $HOME"]

[font]
size = 12.5

[font.normal]
family = "CommitMono"

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"
padding = { x=5, y=5 }
