theme = "rose_pine_moon"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
scrolloff = 999
completion-replace = true
bufferline = "multiple"
true-color = true
popup-border = "all"

[editor.statusline]
left = ["file-name", "file-modification-indicator"]
center = ["version-control", "diagnostics"]
right = ["mode", "spinner"]

[editor.file-picker]
# hidden = true
# ignore = true
# parents = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
"'" = "'"
'<' = '>'

[editor.lsp]
snippets = true

[editor.indent-guides]
render = true
character = "∣"
skip-level = 0

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]

[editor.gutters.line-numbers]
min-width = 1

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

[keys.normal.space]
"w" = ":w"
"q" = ":q"
"Q" = ":q!"
" " = ":config-reload"
"v" = ":sh zellij run -f -c -- gitui"
"e" = ":sh zellij run -f -c -- yazi $PWD"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
