# Python

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

# Rust

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"


[language-server.rust-analyzer.config.cargo]
features = "all"

# Go

[[languages]]
name = "go"
auto-format = true
language-servers = ["golangci-lint-langserver", "gopls"]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "-E",
  "exhaustive",
  "--out-format",
  "json",
  "--issues-exit-code=1",
]

[language-server.gopls]
command = "gopls"

#formatter = { command = "goimports" }

formatter = { command = "golines" }
