
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
